name: jamspell

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]  # [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install c++ dependencies
        run: |
          sudo apt-get install swig4.0 build-essential cmake libgtest-dev -y
#          cd /usr/src/gtest
#          sudo cmake CMakeLists.txt
#          sudo make
#          sudo cp *.a /usr/lib
#          cd -
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt
          mkdir build
          cd build
          cmake ..
          make
          ls -l
          cd ..
          python setup.py install
      - name: Test with pytest
        run: |
          pytest -vv
