name: jamspell publish

on:
  push:
    branches:
      - main
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Verify that git tag matches version
        run: python setup.py verify
      - name: Install build deps
        run: |
          pip install -U pip
          pip install build --user
      - name: Create package
        run: python -m build --sdist --wheel --outdir dist/ .
      # FIXME: Deploy to pypi
      - name: Deploy package to Gemfury
        if: startsWith(github.ref, 'refs/tags')
        run: |
          pip install --user secretstorage twine
          python ~/.local/bin/twine upload dist/* --repository-url https://push.fury.io/${{ secrets.FURY_ORGANIZATION }} -u ${{ secrets.FURY_PUSH_TOKEN }} -p ""